export const convertToNumeric: (input: any) => number;
export const convertToDisplay: (input: any) => string;
export const isValid: (input: any) => boolean;
export const saveBudgetFile: string;
export const passwordNeeded: string;
export const passwordProvided: string;
export const addBudgetItems: string;
export const updateBudgetItem: string;
export const removeBudgetItem: string;
export const budgetItemsChanged: string;
export const getBudgetItems: string;
export const filteredBudgetItems: string;
export const getCategories: string;
export const getCategory: string;
export const addCategory: string;
export const updateCategories: string;
export const storageType: string;
export const fileLocation: string;
export const setFileLocation: string;
export const setFileType: string;
export const setPassword: string;
export const addIncomeItems: string;
export const getExpectedIncome: string;
export const setExpectedIncome: string;
export const getMonthIncome: string;
export const getMonthRangeIncome: string;