name: BuildElectron
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - name: Install node
      uses: actions/setup-node@v1
      with:
          node-version: '10.x'
    
    - name: Check out code
      uses: actions/checkout@v1
    
    - name: Install Yarn
      run: npm install -g yarn

    - name: Install
      run: yarn install --frozen-lockfile

    - name: Build
      run: yarn run build:web

    - name: Package
      run: yarn run build:electron

    - name: Test
      run: yarn run test:native