name: BuildElectron
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - name: Install node
      uses: actions/setup-node@v1
      with:
          node-version: '14.x'
    
    - name: Check out code
      uses: actions/checkout@v1
    
    - name: Install Yarn
      run: npm install -g yarn

    - name: Install
      run: |
        yarn install --frozen-lockfile
        yarn lerna bootstrap

    - name: Install Required dependencies
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get --only-upgrade install google-chrome-stable
        google-chrome --version
        sudo apt-get install xvfb libxtst6 libxss1 libgtk2.0-0 -y
        sudo apt-get install libnss3 libasound2 libgconf-2-4 -y

    - name: Build
      run: yarn run build

    - name: Setup Packaging
      run: cp -a .git src/budgapp/.git

    - name: Package Electron app
      uses: samuelmeuli/action-electron-builder@v1
      with:
        github_token: ${{ secrets.github_token }}
        release: false

    - name: Test
      run: yarn run test:ci

    - name: E2E Ubuntu
      if: startsWith(matrix.os, 'ubuntu')
      run: xvfb-run yarn run test:e2e

    - name: E2E
      if: startsWith(matrix.os, 'windows') || startsWith(matrix.os, 'macos')
      run: yarn run test:e2e

    - name: Capture Failure
      if: ${{ failure() }}
      run: |
        cp -r test/screencaps screencaps
        tar -czvf screencaps.tar.gz screencaps
    
    - name: Upload Failing artifact
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: screencaps
        path: screencaps.tar.gz
