name: BuildElectron
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - name: Install node
      uses: actions/setup-node@v1
      with:
          node-version: '10.x'
    
    - name: Check out code
      uses: actions/checkout@v1
    
    - name: Install Yarn
      run: npm install -g yarn

    - name: Install
      run: yarn install --frozen-lockfile

    - name: Install chrome driver
      if: startsWith(matrix.os, 'ubuntu')
      run: |
      CHROME_VERSION=$(google-chrome --version | cut -f 3 -d ' ' | cut -d '.' -f 1) \
        && CHROMEDRIVER_RELEASE=$(curl --location --fail --retry 3 http://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}) \
        && curl --silent --show-error --location --fail --retry 3 --output /tmp/chromedriver_linux64.zip "http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_RELEASE/chromedriver_linux64.zip" \
        && cd /tmp \
        && unzip chromedriver_linux64.zip \
        && rm -rf chromedriver_linux64.zip \
        && sudo mv chromedriver /usr/local/bin/chromedriver \
        && sudo chmod +x /usr/local/bin/chromedriver \
        && chromedriver --version

    - name: Build
      run: yarn run build:web

    - name: Package Electron app
      uses: samuelmeuli/action-electron-builder@v1
      with:
        github_token: ${{ secrets.github_token }}
        release: false

    - name: Test
      run: yarn run test:ci

    - name: E2E
      run: yarn run test:e2e